version: "3.5"

services:
  webrtc-server:
    container_name: webrtc-server
    restart: always
    networks: 
      - E-skeleton
    build: .
    ports:
      - "8893:8893"
  webrtc-mongo:
    container_name: webrtc_DB
    networks: 
      - E-skeleton
    image: mongo
    ports:
      - "27017:27017"

networks:
  E-skeleton:
    name: E-skeleton-webrtc